name: Audit URLs Across the Website

on:
  workflow_dispatch:
  schedule:
    # At 06:00 AM every 15 days
    - cron: '0 5 */15 * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Audit URLs Across the Website
        run: |
          wget -q https://github.com/Bhupesh-V/areyouok/releases/latest/download/areyouok-linux-amd64
          chmod u+x areyouok-linux-amd64
          ./areyouok-linux-amd64 -i=.git -r=github ./src

      - name: Create an Issue Thread (If Broken URLs Exists)
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: URL Audit Across the Website
          content-path: ./report.github
