name: Build Book & Deploy to Vercel

on: [push]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install mdBook
        run: |
          mkdir bin
          curl https://api.github.com/repos/rust-lang/mdbook/releases/latest \
            | grep "browser_download_url" \
            | grep -Eo 'https://[^\"]*' \
            | xargs wget -O - \
            | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Generate static content for the book
        run: mdbook build

      - name: Setup Node.js (required to install Vercel CLI)
        uses: actions/setup-node@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy static content to Vercel
        run: |
          productionFlag=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            productionFlag="--prod"
          fi

          vercel book --token ${VERCEL_TOKEN} $productionFlag
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
