name: Build Book & Deploy to Vercel

on: [push]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        - uses: XAMPPRocky/deploy-mdbook@v1.1
          with:
              token: ${{ secrets.GITHUB_TOKEN }}
